### PR TITLE
Epic/network memberships handling

### PR DESCRIPTION
**Pull request by leogermani**
This epic branch adds handling of network subscriptions and memberships based on the data made available by https://github.com/Automattic/newspack-network/pull/122

It should be merged only once https://github.com/Automattic/newspack-network/pull/122 has been deployed and we have executed the backfills on every site.

The first PR in this epic branch reverts https://github.com/Automattic/newspack-network/pull/114. (merged)

###  1: https://github.com/Automattic/newspack-network/pull/135

This is a re-implementation of https://github.com/Automattic/newspack-network/pull/114

Testing:

* Create a granted-on-subscription memberships plan on two network sites, and make them synchronised (set same Network ID in the plan settings)
* On the Hub, buy a subscription tied to that membership plan as a reader
* On the Node, Pull all events
* Visit the Node as an anonymous reader and buy a subscription that gives access to the same membership plan using the same email
* Run  `wp newspack-network process-webhooks` in the node to sync events to the Hub
* On the Hub admin, Cancel the subscription
* Confirm the associated Membership is kept active, and that a note is added to the user membership saying it was kept active because there is an active subscription in the Node

###  4: https://github.com/Automattic/newspack-network/pull/137

This is a re-implementation of https://github.com/Automattic/newspack-network/pull/112

Testing: 

* Create a granted-on-subscription memberships plan on two network sites, and make them synchronised (set same Network ID in the plan settings)
* Make sure to sync the latest events by running  `wp newspack-network process-webhooks` and `wp newspack-network sync-all` in the Node 
* you should see the `newspack_network_membership_plan_updated` events in the Event log for both the plan in the hub and the plan in the node
* you also should see that the `newspack_network_membership_plans` option populated in both sites (this is what we tested in #124 
* One one site, buy the subscription, which should grant you the plan
* On the second site, log in/register using the same email address
* On the second site, try to buy the membership-granting subscription – observe it's not allowed

Captura de tela de 2024-08-07 12-42-47

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207352955560208

### CODE REVIEW

**Comment by dkoo** [comment]
> It should be merged only once https://github.com/Automattic/newspack-network/pull/122 has been deployed and we have executed the backfills on every site.

@leogermani I see #122 has been merged—can we proceed with this PR?

**Comment by leogermani** [comment]
> > It should be merged only once https://github.com/Automattic/newspack-network/pull/122 has been deployed and we have executed the backfills on every site.
> 
> @leogermani I see #122 has been merged—can we proceed with this PR?

Yes please. Backfills were executed as well!

**Comment by adekbadek** [comment]
@leogermani – there's an initialization issue. Both in CI and in my local env I see that same `Class "Woocommerce_Memberships\Admin" not found` fatal.

**Comment by leogermani** [comment]
@adekbadek probably a bad merge at some point. But things are working on the child PRs. I don't want to fix this here with the risk of having to resolve conflict with those branches. 

If we review the two child PRs things should end up fine

**Comment by adekbadek** [comment]
Both #135 and #137 are approved, should they be merged to this epic branch?

**Comment by leogermani** [comment]
> Both #135 and #137 are approved, should they be merged to this epic branch?

Yes, I'm gonna address some of your comments there. (I swear I have renamed the variables in those tests before)

But after everyuthing is merged I think we should do another round of tests just to make sure there wasn't any other bad merges... there was a lot of branch juggling and cherry picks here

**Comment by leogermani** [comment]
Feedback addressed and PRs merged. But I didn't test it yet. Once I test everything I'll ask you to have a final look @adekbadek

**Comment by leogermani** [comment]
@adekbadek All looking good in my testing! 

Once we merge this, we can work on also blocking purchases for non-logged in users

**Review by adekbadek — APPROVED** [review]
Re-tested both scenarios, all good!

**Pull request merged**
