### PR TITLE
Fix/backfill duplicate handling

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes two issues:

1. If and event is not persisted in the event log, it should not be processed. 
2. When backfilling `reader_registration` events, disregard `current_page_url` metadata.

By accident this branch also contains #71, but it won't hurt to add that to the `alpha` release.

### How to test the changes in this Pull Request:

0. On `alpha`,
1. Trigger a new `reader_registered` event by registering as a new reader on the site
4. Observe in the Event Log that the event has a `metadata.current_page_url` key in the `data` property
5. Run the backfill for `reader_registered` events (e.g. `wp newspack-network data-backfill reader_registered --start=2024-02-26 --end=2024-12-31 --verbose`)
6. Observe a new `reader_registered` event added, even though a `reader_registered` for this reader is already present
7. Observe that the new event does not have the `metadata.current_page_url` key
8. Switch to this branch, repeat the testing steps, observe the duplicate event is not added 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Tested and looks good for the most part. I am running into one issue while testing though. With these changes checked out, I see that all events will trigger exactly one duplicate before being ignore by the data backfill script.

For example, Here I have created 3 users (test4, test5, and test6@example.com), and each have triggered an initial reader_registered event:

Screenshot 2024-02-27 at 10 28 14

When I run the backfill script the first time, each one triggers an additional reader_registered event:

Screenshot 2024-02-27 at 10 30 12

It isn't until the second time I run this command that duplicates are actually ignored:

Screenshot 2024-02-27 at 10 30 54

Is this expected?

**Comment by adekbadek** [comment]
Not expected, you've uncovered a shortcoming of this solution. It assumes the only metadata missing will be `current_page_url`, but in your example there's also a `referer` metadata key. The solution should be to disregard all `data`. 62fdf8d3755abcafe1d4ed601b35a908f635a2fd should fix it.

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Hmm. I'm still running into an issue, although the behavior has slightly changed. This time, everything but the first of a batch of user registrations is being duplicated. For example, here is test7, 8, and 9. Running the backfill script creates duplicate events for test 8 and 9:
  
Screenshot 2024-02-27 at 10 57 01

**Comment by adekbadek** [comment]
This is a bigger issue than I thought! The code is comparing timestamps. The _event_ will be saved a few milliseconds after the actual _registration_. Thus when looking for an event at time of the registration, it won't be found. Fixed in ee7be33e944b9fbc912404e83a45a4be12909043

**Review by chickenn00dle — APPROVED** [review]
Nice work @adekbadek!

This is working now so gonna give a thumbs up.

I did have one question/nit which is can we simply disregard/drop timestamp as well if the only relevant information we need to consider are email and date? Definitely not a blocker though and something we can revisit if necessary.

**Comment by adekbadek** [comment]
Good suggestion! For registrations that makes sense, because there should be just one per email. The timestamp-range solution should also work for other events, though, and for these disregarding the timestamp altogether is not desirable. There might be many of them, with only the timestamp as differentiator (e.g. donations).

**Pull request merged**
